#
# fixauksia salaisuusksien peittämiseksi
#

#version: "3.8" # Version 3.8 is quite new and should work - WARN `version` is obsolete

services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      #MONGO_INITDB_ROOT_USERNAME: fullstackXXXX
      #MONGO_INITDB_ROOT_PASSWORD: aRgYNpGlHTgYSZpcXXXX
      #MONGO_INITDB_DATABASE: blogAppXXXX
    volumes:
      #- ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./mongo_data:/data/db
  server: # The name of the service, can be anything
    image: blogapp-backend-prod # Declares which image to use
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports: # Declares the ports to publish
      - 3003:3003
    environment:
      #- M-O-N-G-O-D-B_U-R-I=mongodb+srv://fullstackXXXX:aRgYNpGlHTgYSZpcXXXX@cluster0.w6tnp3q.mongodb.net/blogAppXXXX?retryWrites=true&w=majority
      - PORT=3003
      #- S-E-C-R-E-T="salaiXXXXnen"
    depends_on:
      - mongo
